/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProInfanciaRouteImport } from './routes/_authenticated/pro-infancia'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as AuthenticatedContactosProInfanciaRouteImport } from './routes/_authenticated/contactos-pro-infancia'
import { Route as AuthenticatedContactosRouteImport } from './routes/_authenticated/contactos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedProInfanciaChildIdRouteImport } from './routes/_authenticated/pro-infancia.$childId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProInfanciaRoute =
  AuthenticatedProInfanciaRouteImport.update({
    id: '/pro-infancia',
    path: '/pro-infancia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactosProInfanciaRoute =
  AuthenticatedContactosProInfanciaRouteImport.update({
    id: '/contactos-pro-infancia',
    path: '/contactos-pro-infancia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactosRoute = AuthenticatedContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProInfanciaChildIdRoute =
  AuthenticatedProInfanciaChildIdRouteImport.update({
    id: '/$childId',
    path: '/$childId',
    getParentRoute: () => AuthenticatedProInfanciaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/contactos-pro-infancia': typeof AuthenticatedContactosProInfanciaRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/pro-infancia': typeof AuthenticatedProInfanciaRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/pro-infancia/$childId': typeof AuthenticatedProInfanciaChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/contactos': typeof AuthenticatedContactosRoute
  '/contactos-pro-infancia': typeof AuthenticatedContactosProInfanciaRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/pro-infancia': typeof AuthenticatedProInfanciaRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/pro-infancia/$childId': typeof AuthenticatedProInfanciaChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/contactos': typeof AuthenticatedContactosRoute
  '/_authenticated/contactos-pro-infancia': typeof AuthenticatedContactosProInfanciaRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/_authenticated/pro-infancia': typeof AuthenticatedProInfanciaRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/pro-infancia/$childId': typeof AuthenticatedProInfanciaChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/contactos'
    | '/contactos-pro-infancia'
    | '/equipa'
    | '/pro-infancia'
    | '/relatorios'
    | '/pro-infancia/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/contactos'
    | '/contactos-pro-infancia'
    | '/equipa'
    | '/pro-infancia'
    | '/relatorios'
    | '/pro-infancia/$childId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/contactos'
    | '/_authenticated/contactos-pro-infancia'
    | '/_authenticated/equipa'
    | '/_authenticated/pro-infancia'
    | '/_authenticated/relatorios'
    | '/_authenticated/pro-infancia/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro-infancia': {
      id: '/_authenticated/pro-infancia'
      path: '/pro-infancia'
      fullPath: '/pro-infancia'
      preLoaderRoute: typeof AuthenticatedProInfanciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contactos-pro-infancia': {
      id: '/_authenticated/contactos-pro-infancia'
      path: '/contactos-pro-infancia'
      fullPath: '/contactos-pro-infancia'
      preLoaderRoute: typeof AuthenticatedContactosProInfanciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contactos': {
      id: '/_authenticated/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof AuthenticatedContactosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro-infancia/$childId': {
      id: '/_authenticated/pro-infancia/$childId'
      path: '/$childId'
      fullPath: '/pro-infancia/$childId'
      preLoaderRoute: typeof AuthenticatedProInfanciaChildIdRouteImport
      parentRoute: typeof AuthenticatedProInfanciaRoute
    }
  }
}

interface AuthenticatedProInfanciaRouteChildren {
  AuthenticatedProInfanciaChildIdRoute: typeof AuthenticatedProInfanciaChildIdRoute
}

const AuthenticatedProInfanciaRouteChildren: AuthenticatedProInfanciaRouteChildren =
  {
    AuthenticatedProInfanciaChildIdRoute: AuthenticatedProInfanciaChildIdRoute,
  }

const AuthenticatedProInfanciaRouteWithChildren =
  AuthenticatedProInfanciaRoute._addFileChildren(
    AuthenticatedProInfanciaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedContactosRoute: typeof AuthenticatedContactosRoute
  AuthenticatedContactosProInfanciaRoute: typeof AuthenticatedContactosProInfanciaRoute
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedProInfanciaRoute: typeof AuthenticatedProInfanciaRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedContactosRoute: AuthenticatedContactosRoute,
  AuthenticatedContactosProInfanciaRoute:
    AuthenticatedContactosProInfanciaRoute,
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedProInfanciaRoute: AuthenticatedProInfanciaRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
